server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8671/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8083"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1
        - id: department-service
          uri: http://localhost:8082
          predicates:
            - Path=/department/**
          filters:
            - StripPrefix=1